feat: API JWT authentication
betagouv/recommandations-collaboratives pull request #347
Opened 2024-05-07 14:07 UTC by etchegom

Il s'agit de :
- [ ] Une correction de bug
- [ ] Une nouvelle fonctionnalité programmée
- [ ] Une nouvelle fonctionnalité spontanée

## Décrivez vos changements
Soit en texte, soit en images ou les deux.

=> Liens vers des éléments de Github Issue, Trello, ...

## Checklist d'acceptation de revue de code
- [ ] Aucun texte ne fait référence à du vocabulaire spécifique d'un métier
- [ ] Mon code est auto-documenté ou la documentation a été mise à jour/créée
- [ ] La gestion du multi-portail a été prise en compte
- [ ] L'accessibilité a été prise en compte
- [ ] Pre-commit est configuré et a été lancé
- [ ] Des tests couvrant le code changé ont été ajoutés/modifiés
- [ ] L'ensemble des tests front et back sont au vert

## Demandes
- [ ] Je souhaite un déploiement en préproduction

2024-05-07 14:12 UTC, glibersat requested changes
Re @etchegom , attention, le multiportail n'a pas été pris en compte je pense :)

2024-05-13 06:34 UTC, glibersat commented
Salut,

Pour s'en assurer, est-ce que tu pourrais faire deux tests ?
1. Si un utilisateur n'est pas déclaré sur la plateforme X, il ne peut pas avoir un token
2. Si un token a été obtenu sur la plateforme X, qu'il ne puisse pas être utilisé sur la plateforme Y

Merci !

2024-05-14 09:02 UTC, etchegom commented
Après vérification, un utilisateur peut s'authentifier sur n'importe quel site en login classique, c'est le cas également en login API (on passe par les même backend d'authentification).
J'ai tout de même ajouter un test pour vérifier les claims ajoutés dans le token.

2024-05-14 09:10 UTC, etchegom commented on recoco/urls.py
> +    path("api/", include(rest_api_urls)),
Pourquoi pas faire aussi ce changement dans une prochaine PR:
```python
path("api/", include(rest_api_urls, namespace="api")),
```

2024-05-14 11:37 UTC, glibersat commented on recoco/urls.py
> +    path("api/", include(rest_api_urls)),
oui sans problème ; bien vérifier dans les fichiers JS & HTML s'il n'y a pas des références existantes à prefixer par api: du coup

2024-05-21 16:41 UTC, glibersat approved these changes

2024-05-21 16:41 UTC, merged