Add deletion policy for resources
betagouv/recommandations-collaboratives pull request #640
Opened 2024-09-02 13:54 UTC by bastien-rcc

Il s'agit de :
- [ ] Une correction de bug
- [ ] Une nouvelle fonctionnalité programmée
- [ ] Une nouvelle fonctionnalité spontanée

## Décrivez vos changements
Soit en texte, soit en images ou les deux.

=> Liens vers des éléments de Github Issue, Trello, ...

## Checklist d'acceptation de revue de code
- [ ] Aucun texte ne fait référence à du vocabulaire spécifique d'un métier
- [ ] Mon code est auto-documenté ou la documentation a été mise à jour/créée
- [ ] La gestion du multi-portail a été prise en compte
- [ ] L'accessibilité a été prise en compte
- [ ] Pre-commit est configuré et a été lancé
- [ ] Des tests couvrant le code changé ont été ajoutés/modifiés
- [ ] L'ensemble des tests front et back sont au vert

## Demandes
- [ ] Je souhaite un déploiement en préproduction

2024-09-02 14:02 UTC, bastien-rcc commented on recoco/apps/resources/views.py
> +        if request.site == self.object.site_origin and self.object.sites.count() == 1:
j'ai un doute sur la logique et son implémentation

2024-09-02 14:03 UTC, bastien-rcc commented on recoco/apps/resources/views.py
> +        # how do we notify the user of the reasons they can't delete ?
et au cas où l'effacement ne serait pas autorisé, je me demande comment en notifier l'utilisateur.ice

2024-09-02 14:12 UTC, glibersat commented on recoco/apps/resources/views.py
> +        # how do we notify the user of the reasons they can't delete ?
https://docs.djangoproject.com/en/5.0/ref/contrib/messages/

2024-09-02 14:53 UTC, bastien-rcc commented
dépend de #617

2024-09-02 16:23 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +                          site_origin=current_site
je vais avoir besoin de #617 pour test ou bien je dois trouver une autre stratégie

2024-09-05 06:31 UTC, glibersat requested changes
Voilà pour la 1ère review :)

2024-09-05 06:31 UTC, glibersat commented on recoco/apps/resources/views.py
> +        site_is_referenced = self.request.site in self.get_object().sites.all()
Est-ce que c'est vraiment nécessaire de garder ça maintenant ? Au pire, ça supprimerait le site courant qui n'existe pas dans la liste, non ?

2024-09-05 06:31 UTC, glibersat commented on recoco/apps/resources/tests/test_views.py
> +def test_delete_resource_not_referenced_not_possible_for_staff(client, request):
Quelle est la différence avec le test du dessus ? ( :488 )

2024-09-05 06:31 UTC, glibersat commented on recoco/apps/resources/tests/test_views.py
> +def test_update_resource_by_non_site_origin_and_redirect(request, client):
from_non_origin_site plutot ?

2024-09-05 06:31 UTC, glibersat commented on recoco/apps/resources/tests/test_views.py
> +def test_update_resource_by_site_origin_and_redirect(request, client):
from_origin_site plutôt ?

2024-09-05 06:31 UTC, glibersat commented on recoco/apps/resources/tests/test_views.py
> +    resource = baker.make(models.Resource)
je te conseille de fixer la date car on la référence (tu peux utiliser la date courante par ex)

2024-09-05 07:15 UTC, bastien-rcc commented on recoco/apps/resources/views.py
> +        site_is_referenced = self.request.site in self.get_object().sites.all()
En effet, c'est exact. J'aimais bien définir le périmètre explicitement mais techniquement ce n'est pas obligatoire. Je peux l'enlever.

2024-09-05 09:56 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +def test_update_resource_by_site_origin_and_redirect(request, client):
ok

2024-09-05 09:58 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +    resource = baker.make(models.Resource)
il y a un défaut à `timezone.now`ça devrait suffire ? ou bien je n'ai pas compris ?

2024-09-05 09:59 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +def test_update_resource_by_non_site_origin_and_redirect(request, client):
ok

2024-09-05 10:02 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +def test_delete_resource_not_referenced_not_possible_for_staff(client, request):
le `not_available` était pour tester le `get`et donc s'il ça s'affichait et le `not_possible` était pour tester le `post` et donc si il était possible de faire la requête. Mais de toutes façons j'ai enlevé ces tests puisque suite à ton commentaire suivant on ne fait plus le check si le site est référencé ou non.

2024-09-10 16:59 UTC, glibersat requested changes
Hello @bastien-rcc , voici mes retours, merci

2024-09-11 12:12 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +        "content": "this is some updated content",
c'est corrigé

2024-09-11 12:25 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +    resource = baker.make(models.Resource)
c'est fait

2024-09-11 12:26 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +        _ = client.get(url)
c'est fait

2024-09-11 12:36 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
> +    assert models.Resource.on_site.all().count() == 1
je compte désormais toutes les ressources, c'est plus complet en effet.

2024-09-11 12:56 UTC, bastien-rcc commented on recoco/apps/resources/tests/test_views.py
>      assertContains(response, 'form id="form-resource-delete"')
c'est ajouté

2024-09-11 13:10 UTC, bastien-rcc commented on recoco/apps/resources/views.py
> +            self.object.deleted = timezone.now()
en effet, c'est corrigé

2024-09-11 13:16 UTC, bastien-rcc commented on recoco/apps/resources/views.py
>          self.object.save()
`resource.deleted` a besoin du save alors que `resource.sites.remove()` n'en a pas besoin. Effectivement le `save()` est uniquement nécessaire dans le if. Je l'ai déplacé.

2024-09-11 13:58 UTC, bastien-rcc commented on recoco/apps/resources/views.py
>                  form.save_m2m()
exact, et en plus j'ai sorti les lignes en rapport avec les sites du with car elles n'ont rien à voir avec la revision. J'ai également ajouté le test.
Par contre, je me demande si c'est la bonne PR pour faire ça étant donné que c'est déjà fait dans la PR correspondante : #617 . Je l'avais ajouté manuellement simplement pour tester la logique car la #617 allait être released.

2024-09-11 16:12 UTC, bastien-rcc commented on recoco/apps/resources/views.py
>      if request.method == "POST":
Oui, j'ai changé l'implémentation complète, ce qui devrait répondre à ce problème.

2024-09-11 16:13 UTC, bastien-rcc commented on recoco/apps/resources/views.py
> +            resource.sites.remove(request.site)
c'est vrai, j'ai changé l'implémentation pour utiliser une logique qui je pense est beaucoup plus propre. Je te laisse regarder à nouveau.

2024-09-11 16:21 UTC, bastien-rcc commented
@glibersat merci pour les commentaires.

J'ai réimplémenté la logique. Je ne crée plus de copie de la ressource au moment de l'édition.
Au moment de l'édition si je vois que la ressource est éditée par un site tiers, alors je renvoie vers la page de création de ressource, avec  les `initial_data` de la ressource d'origine. Et, au moment de la sauvegarde, j'applique la logique sur les `sites` et `site_origin` de la ressource d'origine et je crée simplement une nouvelle ressource basée sur les données de l'ancienne et appartenant au site courant. 

Je pense que c'est beaucoup plus propre. Ça fonctionne bien depuis l'interface web. J'ai juste le test qui édite la ressource depuis un site tiers qui ne passe pas pour le moment. Mais puisque ça fonctionne depuis l'interface web je pense que c'est mon test qui est erroné, je ne vois juste pas encore où se trouve la faille. 

Je veux bien avoir ton avis.

2024-09-12 06:51 UTC, glibersat requested changes
Hello @bastien-rcc , voici mes derniers retours

2024-09-12 06:51 UTC, glibersat commented on recoco/apps/resources/views.py
> +def resource_create(request, shared_resource_id=None):
Je ne comprends pas pourquoi tu as créé une 2ème URL pour la copie d'une ressource existante. Peux tu m'expliquer ? merci

2024-09-12 06:51 UTC, glibersat commented on recoco/apps/resources/views.py
> +        shared_resource_as_dict = model_to_dict(shared_resource)
As tu pu vérifier que le dict embarquer toutes les données dont on a besoin (je pense aux m2m) ? Dans les tests, je vois un test sur une FK mais pas sur une M2M qui est censée être remplie.
Est-ce que ton code crée une révision initiale pour la nouvelle ressource ? (à vérifier dans le test)

2024-09-23 08:29 UTC, merged