Fix/change resource UI
betagouv/recommandations-collaboratives pull request #865
Opened 2024-12-09 09:01 UTC by Louifine

Il s'agit de :
- [x] Une correction de bug
- [x] Une nouvelle fonctionnalité programmée
- [ ] Une nouvelle fonctionnalité spontanée

## Décrivez vos changements
Changement des boutons pour la gestion des recommandations d'un projet : 
<img width="416" alt="image" src="https://github.com/user-attachments/assets/b24ebfde-5b7d-465f-9416-0b90be5ed9f8">

Suppression des indications brouillon et modification du titre de la page des ressources suggérées : 
<img width="938" alt="image" src="https://github.com/user-attachments/assets/c98a2e33-e763-47b3-8e6f-a2bb1048495b">

## Checklist d'acceptation de revue de code
- [x] Aucun texte ne fait référence à du vocabulaire spécifique d'un métier
- [x] Mon code est auto-documenté ou la documentation a été mise à jour/créée
- [x] La gestion du multi-portail a été prise en compte
- [x] L'accessibilité a été prise en compte
- [x] Pre-commit est configuré et a été lancé
- [x] Des tests couvrant le code changé ont été ajoutés/modifiés
- [x] L'ensemble des tests front et back sont au vert

## Demandes
- [ ] Je souhaite un déploiement en préproduction

2024-12-12 08:52 UTC, glibersat commented on recoco/settings/frontend_tests.py
> +# GDAL_LIBRARY_PATH="/opt//homebrew/lib/libgdal.dylib"
Surcharge de ta machine qui n'aurait pas du être publiée ! A revert, merci :)

2024-12-12 08:52 UTC, glibersat requested changes
le GDAL est on est bon :)

2024-12-12 10:56 UTC, Louifine commented
j'ai pas revert mais j'ai remis le fichier dev test comme il était, tu me diras si c'est good @glibersat

2024-12-12 18:47 UTC, glibersat commented
@Louifine nope, tjs pas, c'était sensé être commenté. Merci de revert le fichier plutôt que multi commiter :)

2025-01-06 13:30 UTC, glibersat approved these changes

2025-01-06 13:30 UTC, glibersat commented on frontend_tests/cypress/e2e/project/tasks/canSeeKanbanTasks.cy.js
> +    cy.becomeAdvisor(currentProject.pk); // A remplacer par une fixture avec un user déjà advisor du projet
Bonne pratique : ajoute le mot clé FIXME devant ton commentaire, comme ça tu pourras retrouver tes dettes facilement (et ton IDE doit le surligner probablement)

2025-01-06 13:30 UTC, merged