[feat] add dailymotion cookies informations
betagouv/recommandations-collaboratives pull request #874
Opened 2024-12-10 08:47 UTC by Louifine

Il s'agit de :
- [ ] Une correction de bug
- [x] Une nouvelle fonctionnalité programmée
- [ ] Une nouvelle fonctionnalité spontanée

## Décrivez vos changements
Modification des informations relatives aux cookies pour y ajouter les informations des cookies de dailymotion.

Cete PR est liée avec [celle du multisites.](https://github.com/betagouv/recoco-portails/pull/109)

## Checklist d'acceptation de revue de code
- [x] Aucun texte ne fait référence à du vocabulaire spécifique d'un métier
- [x] Mon code est auto-documenté ou la documentation a été mise à jour/créée
- [x] La gestion du multi-portail a été prise en compte
- [x] L'accessibilité a été prise en compte
- [x] Pre-commit est configuré et a été lancé
- [x] Des tests couvrant le code changé ont été ajoutés/modifiés
- [x] L'ensemble des tests front et back sont au vert

## Demandes
- [ ] Je souhaite un déploiement en préproduction

2024-12-10 08:48 UTC, Louifine commented
@glibersat lorsque j'ai voulu supprimer les cookies de youtube, un message me prévenant que c'était lié à d'autres info (cookie group, et des cookies utilisateurs je pense), je n'ai pas osé valider en me disant qu'il fallait surement supprimer en cascade.

2024-12-12 08:37 UTC, glibersat requested changes
Il y a encore des vidéos youtube référencées : `multisites/templates/urbanvitaliz.fr/home/home.html`

Donc, soit supprimer ces vidéos, soit ne pas supprimer les cookies

2024-12-12 11:01 UTC, Louifine commented
@glibersat j'ai remis youtube tout en laissant dailymotion dans la privacy policiy et j'ai laissé le cookie youtube dans l'admin d'UV, normalement c'est tout bon

2024-12-30 08:40 UTC, glibersat commented
Hello @Louifine , merci pour les modifs. Je me rends compte que le privacy.html est statique concernant les cookies : ça ne devrait pas être le cas. En effet, tu as la liste des cookies en base et ce tableau doit se mettre à jour automatiquement si on en ajoute/retire

2025-01-06 08:06 UTC, Louifine commented
Hello @glibersat c'est noté, je l'ajoute à ma to do de la rentrée

2025-01-09 07:24 UTC, merged