[feat] add files from edl to files page
betagouv/recommandations-collaboratives pull request #876
Opened 2024-12-10 12:53 UTC by Louifine

Il s'agit de :
- [ ] Une correction de bug
- [x] Une nouvelle fonctionnalité programmée
- [ ] Une nouvelle fonctionnalité spontanée

## Décrivez vos changements
Ajout de fichier venant de l'edl dans la page des fichiers diponibles.
Création d'un filtre spécifique poru obtenir la fin d'un path.

Resolve [#523](https://github.com/betagouv/recommandations-collaboratives/issues/523)

## Checklist d'acceptation de revue de code
- [x] Aucun texte ne fait référence à du vocabulaire spécifique d'un métier
- [x] Mon code est auto-documenté ou la documentation a été mise à jour/créée
- [x] La gestion du multi-portail a été prise en compte
- [x] L'accessibilité a été prise en compte
- [x] Pre-commit est configuré et a été lancé
- [ ] Des tests couvrant le code changé ont été ajoutés/modifiés
- [x] L'ensemble des tests front et back sont au vert

## Demandes
- [ ] Je souhaite un déploiement en préproduction

2024-12-10 12:54 UTC, Louifine commented
@glibersat je ferai les tests asociés demain, pour avancer sur l'autre tâche sur laquelle j'aurai surement besoin de back

2025-01-06 08:16 UTC, glibersat commented
petit ping pour les tests @Louifine :)

2025-01-06 08:50 UTC, Louifine commented
@glibersat yes c'est dans les tuyaux !

2025-01-06 14:05 UTC, glibersat requested changes
Utiliser `filename` à la place du filtre ajouté
https://docs.djangoproject.com/en/5.0/ref/models/fields/#filefield

2025-01-07 10:05 UTC, closed without merging